// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZBGAmXGrdnO30Tnj7lmnlFpGMfJJAP4',
    appId: '1:422262636347:web:a3e7153cff3a8ee854411e',
    messagingSenderId: '422262636347',
    projectId: 'routine-24',
    authDomain: 'routine-24.firebaseapp.com',
    storageBucket: 'routine-24.firebasestorage.app',
    measurementId: 'G-V4ZQS32LKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx--fGopdSLX1iN8FEW63JoCsGgWA16KY',
    appId: '1:422262636347:android:25bcf722de6443e954411e',
    messagingSenderId: '422262636347',
    projectId: 'routine-24',
    storageBucket: 'routine-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9UHr90jfMsMAj8xO3belBgL-p6KAQzys',
    appId: '1:422262636347:ios:8f50b0dcb6038f7b54411e',
    messagingSenderId: '422262636347',
    projectId: 'routine-24',
    storageBucket: 'routine-24.firebasestorage.app',
    iosBundleId: 'com.dashpill.routine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9UHr90jfMsMAj8xO3belBgL-p6KAQzys',
    appId: '1:422262636347:ios:0b510a82d2cc676854411e',
    messagingSenderId: '422262636347',
    projectId: 'routine-24',
    storageBucket: 'routine-24.firebasestorage.app',
    iosBundleId: 'com.example.routine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkZBGAmXGrdnO30Tnj7lmnlFpGMfJJAP4',
    appId: '1:422262636347:web:62c21b0a4fafc35254411e',
    messagingSenderId: '422262636347',
    projectId: 'routine-24',
    authDomain: 'routine-24.firebaseapp.com',
    storageBucket: 'routine-24.firebasestorage.app',
    measurementId: 'G-PDZYL13Y5J',
  );
}
